// @ts-nocheck
/**
 * captureCurrentGlobalConfig。自 bundle 抽出，逐字搬运、行为不变。
 */
import { useCallback, useMemo } from "react";
import { cloneBackupValue } from "../lib/backup";
import { normalizeUnifiedApiConfigs } from "../lib/unified-api-config";

export function use_captureCurrentGlobalConfig(deps: any) {
  const {
    apiConfigs,
    audioApiConfigId,
    audioApiKey,
    audioApiUrl,
    audioModelApiBindings,
    audioModelProtocolBindings,
    audioModels,
    configButlerDocUrl,
    configButlerMode,
    configButlerTargetApiConfigId,
    configButlerTargetCategory,
    imageApiConfigId,
    imageApiKey,
    imageApiUrl,
    imageCompatResolutions,
    imageModelApiBindings,
    imageModelProtocolBindings,
    imageModels,
    modelProtocolRegistry,
    seedanceDurations,
    seedanceEnableWebSearch,
    seedanceGenerateAudio,
    seedanceModel,
    seedanceRatios,
    seedanceResolutions,
    seedanceVirtualPortraits,
    seedanceWatermark,
    textApiConfigId,
    textApiKey,
    textApiUrl,
    textModelApiBindings,
    textModelProtocolBindings,
    textModels,
    tianjiSeedanceModel,
    tongyiWanxiangDurations,
    tongyiWanxiangEditModels,
    tongyiWanxiangImageModels,
    tongyiWanxiangRatios,
    tongyiWanxiangReferenceImageModels,
    tongyiWanxiangResolutions,
    tongyiWanxiangTextModels,
    ttsMusicModel,
    videoApiConfigId,
    videoApiKey,
    videoApiUrl,
    videoAspectRatios,
    videoDurations,
    videoModelApiBindings,
    videoModelProtocolBindings,
    videoModelRequestProfilesText,
    videoModels,
    videoResolutions,
  } = deps;
  const captureCurrentGlobalConfig = () => ({
      apiConfigs: cloneBackupValue(normalizeUnifiedApiConfigs(apiConfigs)),
      textApiConfigId: textApiConfigId,
      imageApiConfigId: imageApiConfigId,
      videoApiConfigId: videoApiConfigId,
      audioApiConfigId: audioApiConfigId,
      textApiUrl: textApiUrl,
      textApiKey: textApiKey,
      imageApiUrl: imageApiUrl,
      imageApiKey: imageApiKey,
      videoApiUrl: videoApiUrl,
      videoApiKey: videoApiKey,
      audioApiUrl: audioApiUrl,
      audioApiKey: audioApiKey,
	                      textModel: textModels,
	                      drawingModel: imageModels,
	                      imageCompatResolutions: imageCompatResolutions,
	                      videoModel: videoModels,
      audioModel: audioModels,
      ttsMusicModel: ttsMusicModel,
      videoDurations: videoDurations,
      videoResolutions: videoResolutions,
      videoAspectRatios: videoAspectRatios,
      videoModelRequestProfiles: videoModelRequestProfilesText,
      seedanceModel: seedanceModel,
      tianjiSeedanceModel: tianjiSeedanceModel,
      seedanceDurations: seedanceDurations,
      seedanceResolutions: seedanceResolutions,
      seedanceRatios: seedanceRatios,
      seedanceGenerateAudio: seedanceGenerateAudio,
      seedanceWatermark: seedanceWatermark,
      seedanceEnableWebSearch: seedanceEnableWebSearch,
      seedanceVirtualPortraits: cloneBackupValue(seedanceVirtualPortraits),
      tongyiWanxiangTextModels: tongyiWanxiangTextModels,
      tongyiWanxiangReferenceImageModels: tongyiWanxiangReferenceImageModels,
      tongyiWanxiangImageModels: tongyiWanxiangImageModels,
      tongyiWanxiangEditModels: tongyiWanxiangEditModels,
      tongyiWanxiangDurations: tongyiWanxiangDurations,
      tongyiWanxiangResolutions: tongyiWanxiangResolutions,
      tongyiWanxiangRatios: tongyiWanxiangRatios,
      modelProtocolRegistry: cloneBackupValue(modelProtocolRegistry),
      configButlerDocUrl: configButlerDocUrl,
      configButlerMode: configButlerMode,
      configButlerTargetCategory: configButlerTargetCategory,
      configButlerTargetApiConfigId: configButlerTargetApiConfigId,
      textModelApiBindings: cloneBackupValue(textModelApiBindings),
      textModelProtocolBindings: cloneBackupValue(textModelProtocolBindings),
      imageModelApiBindings: cloneBackupValue(imageModelApiBindings),
      imageModelProtocolBindings: cloneBackupValue(imageModelProtocolBindings),
      videoModelApiBindings: cloneBackupValue(videoModelApiBindings),
      videoModelProtocolBindings: cloneBackupValue(videoModelProtocolBindings),
      audioModelApiBindings: cloneBackupValue(audioModelApiBindings),
      audioModelProtocolBindings: cloneBackupValue(audioModelProtocolBindings),
    });
  return { captureCurrentGlobalConfig };
}
