created: 2026-07-10T15:54:13.238Z
updated: 2026-07-10T15:55:07.763Z
update_count: 2
last_field: diagram
kind: nested-class
title: storage-assets
children:
  - backup
  - cleanup
  - migrations
  - safety-snapshots
  - storage-mirror
parentPath: []
